Allow different timestamp formats in Google exports to be parsed
Freika/dawarich pull request #281
Opened 2024-09-24 20:51 UTC by saschazepter

Older exports may have timestamps in millisecond format, i. e. `startTimestampMs` instead of `startTimestamp` and `timestampMs` instead of `timestamp`. This might make the import of a `Location History.json` or `Records.json` fail or leaving back zero imports at all.

The changed files will help these files getting parsed correctly.

2024-09-28 15:02 UTC, Freika requested changes
Thank you for taking care of this issue! Although, there is some changes to be made.

2024-09-28 15:02 UTC, Freika commented on app/services/google_maps/records_parser.rb
> +  def parse_timestamp(timestamp)
This method is the same across `app/services/google_maps/records_parser.rb` and `app/services/google_maps/semantic_history_parser.rb`. Can you please move it to a module so it wouldn't be repeated?

Also tests for both cases (with `timestamp` and `timestampMs`) would be great to have.

2024-09-28 15:13 UTC, Freika commented on app/services/google_maps/records_parser.rb
> +  def parse_timestamp(timestamp)
Master branch now has tests for both classes changed in this PR, so you can take them as an example

2024-09-29 14:51 UTC, saschazepter commented on app/services/google_maps/records_parser.rb
> +  def parse_timestamp(timestamp)
Where would you move the ```parse_timestamp``` method? i would place it in the ```application_helper.rb```.

2024-09-29 15:31 UTC, Freika commented on app/services/google_maps/records_parser.rb
> +  def parse_timestamp(timestamp)
Code defined in helpers by default is only available in views, not in service classes. I'd place it in module somewhere in /lib/timestamps.rb, for example

2024-10-03 11:49 UTC, Freika commented
@saschazepter is it ready for review?

2024-10-03 21:06 UTC, saschazepter commented
> @saschazepter is it ready for review?

Not with the tests yet.

2024-10-18 11:37 UTC, Freika approved these changes
Great job, thank you for fixing it!

2024-10-18 11:37 UTC, merged